name: Build on DockerHub

on:
  push:
    branches: ["main"] # Opcional: roda o workflow apenas em pushes para a branch main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: messyas/webacademy:latest
          # dockerfile: ./Dockerfile  # Descomente se o seu Dockerfile não estiver na raiz

  deploy:
    runs-on: ubuntu-latest
    needs: build # Garante que o deploy só roda se o job 'build' for bem-sucedido
    steps:
      - name: Fazendo deploy
        run: echo "Deploy com sucesso!"
